// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, type MutationOptions, queryOptions } from "@tanstack/solid-query";

import { client } from "../client.gen";
import { callTool, deleteSession, health, listSessions, listTools, type Options } from "../sdk.gen";
import type {
  CallToolData,
  CallToolError,
  CallToolResponse,
  DeleteSessionData,
  HealthData,
  HealthResponse2,
  ListSessionsData,
  ListSessionsResponse,
  ListToolsData,
  ListToolsResponse,
} from "../types.gen";

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseUrl" | "body" | "headers" | "path" | "query"> & {
    _id: string;
    _infinite?: boolean;
    tags?: ReadonlyArray<string>;
  },
];

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0];
  if (infinite) {
    params._infinite = infinite;
  }
  if (tags) {
    params.tags = tags;
  }
  if (options?.body) {
    params.body = options.body;
  }
  if (options?.headers) {
    params.headers = options.headers;
  }
  if (options?.path) {
    params.path = options.path;
  }
  if (options?.query) {
    params.query = options.query;
  }
  return [params];
};

export const healthQueryKey = (options?: Options<HealthData>) => createQueryKey("health", options);

export const healthOptions = (options?: Options<HealthData>) =>
  queryOptions<HealthResponse2, DefaultError, HealthResponse2, ReturnType<typeof healthQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await health({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: healthQueryKey(options),
  });

export const listSessionsQueryKey = (options?: Options<ListSessionsData>) =>
  createQueryKey("listSessions", options);

/**
 * List saved sessions (most recent first).
 */
export const listSessionsOptions = (options?: Options<ListSessionsData>) =>
  queryOptions<
    ListSessionsResponse,
    DefaultError,
    ListSessionsResponse,
    ReturnType<typeof listSessionsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listSessions({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listSessionsQueryKey(options),
  });

/**
 * Delete a session by ID.
 */
export const deleteSessionMutation = (
  options?: Partial<Options<DeleteSessionData>>,
): MutationOptions<unknown, DefaultError, Options<DeleteSessionData>> => {
  const mutationOptions: MutationOptions<unknown, DefaultError, Options<DeleteSessionData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteSession({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};

export const listToolsQueryKey = (options?: Options<ListToolsData>) =>
  createQueryKey("listTools", options);

export const listToolsOptions = (options?: Options<ListToolsData>) =>
  queryOptions<
    ListToolsResponse,
    DefaultError,
    ListToolsResponse,
    ReturnType<typeof listToolsQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await listTools({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      });
      return data;
    },
    queryKey: listToolsQueryKey(options),
  });

export const callToolMutation = (
  options?: Partial<Options<CallToolData>>,
): MutationOptions<CallToolResponse, CallToolError, Options<CallToolData>> => {
  const mutationOptions: MutationOptions<CallToolResponse, CallToolError, Options<CallToolData>> = {
    mutationFn: async (fnOptions) => {
      const { data } = await callTool({
        ...options,
        ...fnOptions,
        throwOnError: true,
      });
      return data;
    },
  };
  return mutationOptions;
};
