// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type AguiChatRequest = {
    messages: Array<ChatMsg>;
    run_id?: string | null;
    thread_id?: string | null;
    tools: Array<ToolDef>;
};

export type AgentPart = {
    id: string;
    messageId: string;
    name: string;
    sessionId: string;
    source?: null | AgentPartSource;
    type: string;
};

export type AgentPartSource = {
    end: number;
    start: number;
    value: string;
};

export type ChatMsg = {
    content?: unknown;
    id?: string | null;
    name?: string | null;
    role: string;
    tool_call_id?: string | null;
    tool_calls?: Array<ToolCallWire> | null;
};

export type FilePart = {
    filename?: string | null;
    id: string;
    messageId: string;
    mime: string;
    sessionId: string;
    source?: null | FilePartSource;
    type: string;
    url: string;
};

export type FilePartSource = {
    path: string;
    text: PartTextRange;
    type: string;
};

export type HealthResponse = {
    status: string;
    tool_count: number;
    provider: string;
    model: string;
    mcp: number;
};

export type PartTextRange = {
    end: number;
    start: number;
    value: string;
};

export type PartTime = {
    end?: number | null;
    start: number;
};

export type TextPart = {
    id: string;
    ignored?: boolean | null;
    messageId: string;
    metadata?: unknown;
    sessionId: string;
    synthetic?: boolean | null;
    text: string;
    time?: null | PartTime;
    type: string;
};

export type ToolCallFuncWire = {
    arguments: string;
    name: string;
};

export type ToolCallRequest = {
    arguments: unknown;
};

export type ToolCallWire = {
    function: ToolCallFuncWire;
    id: string;
    type: string;
};

export type ToolDef = {
    description: string;
    name: string;
    parameters: unknown;
};

export type ToolInfo = {
    description: string;
    name: string;
    parameters: unknown;
};

export type ToolResult = {
    content: string;
    is_error: boolean;
    metadata?: unknown;
};

export type HealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthResponses = {
    /**
     * Server health status
     */
    200: HealthResponse;
};

export type HealthResponse2 = HealthResponses[keyof HealthResponses];

export type ListToolsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/tools';
};

export type ListToolsResponses = {
    /**
     * List all available tools
     */
    200: Array<ToolInfo>;
};

export type ListToolsResponse = ListToolsResponses[keyof ListToolsResponses];

export type CallToolData = {
    body: ToolCallRequest;
    path: {
        /**
         * Tool name
         */
        name: string;
    };
    query?: never;
    url: '/tools/{name}';
};

export type CallToolErrors = {
    /**
     * Tool not found
     */
    404: string;
    /**
     * Tool execution failed
     */
    500: string;
};

export type CallToolError = CallToolErrors[keyof CallToolErrors];

export type CallToolResponses = {
    /**
     * Tool execution result
     */
    200: ToolResult;
};

export type CallToolResponse = CallToolResponses[keyof CallToolResponses];
